### ISSUE TITLE
请问这是什么问题

### ISSUE THREAD

**Issue by HakFoo** [codyi96/auto-buy#3]
![61V3BHTDDCJ`FSIC)QE@`EK](https://user-images.githubusercontent.com/32438472/69915571-8570e700-148b-11ea-9255-87775d445351.png)

**Comment by HakFoo** [comment]
![61V3BHTDDCJ`FSIC)QE@`EK](https://user-images.githubusercontent.com/32438472/69915593-c668fb80-148b-11ea-9695-e04ff1fe1b97.png)

**Comment by HakFoo** [comment]
<img src="http://ww1.sinaimg.cn/large/005GDBl4gy1g9hlprqxchj312x02sdg5.jpg"/>

**Comment by codyi96** [comment]
Chrome版本与驱动版本不匹配。
脚本使用的驱动存储在工程根目录下的`drivers `文件夹中，参考的Chrome版本为77.0.3865.90。
你可以检查你的Chrome版本并到[这里](https://chromedriver.chromium.org/home)下载对应的驱动替换之。😊

**Comment by HakFoo** [comment]
版本没错,重新开两次之后又不报错了,不过好像用不了

**Comment by codyi96** [comment]
> 版本没错,重新开两次之后又不报错了,不过好像用不了

已收悉，方便的话烦请详述下无法使用情况下的表现。
最近较忙，如确有问题，过几天会修复。
